---
# This playbook introduces the concept of roles to separate the task and not make this playbook too cluttered.

- hosts: all
  become: true
  pre_tasks:

  - name: Update apt repository
    tags: always 
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Update dnf repository
    tags: always
    dnf:
      update_cache: yes
    when: ansible_distribution in ["CentOS"]
    
- hosts: all
  become: true
  roles:
  - base  

- hosts: web_servers 
  become: true
  roles:
  - web_servers # Ansible will look for the folder './roles/web_servers' and execute the tasks in main.yml

- hosts: db_servers 
  become: true
  roles:
  - db_servers

- hosts: workstations
  become: true
  roles:
  - workstations
