  - name: Install unzip
    apt:
      name: unzip
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]
  - name: Download and unzip terraform binary
    become: true
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      owner: root
      group: root
      mode: 0755
